namespace StoresEnum {
  export enum Status {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    STOPPED = "STOPPED",
  }

  export const StatusLabel = {
    [Status.ACTIVE]: "Active",
    [Status.INACTIVE]: "Inactive",
    [Status.STOPPED]: "Stopped",
  };

  export const StatusColor = {
    [Status.ACTIVE]: "success",
    [Status.INACTIVE]: "warning",
    [Status.STOPPED]: "red",
  };

  export const StatusBadgeColor = {
    [Status.ACTIVE]: "green",
    [Status.INACTIVE]: "yellow",
    [Status.STOPPED]: "red",
  };

  export enum PhoneTypes {
    MOBILE = "MOBILE",
    HOME = "HOME",
    BUSINESS = "BUSINESS",
    OTHER = "OTHER",
  }

  export const PhoneTypesLabels = {
    [PhoneTypes.MOBILE]: "Mobile",
    [PhoneTypes.HOME]: "Home",
    [PhoneTypes.BUSINESS]: "Business",
    [PhoneTypes.OTHER]: "Other",
  };

  export enum PhoneNumberMessenger {
    WHATSAPP = "WHATSAPP",
    TELEGRAM = "TELEGRAM",
    MESSENGER = "MESSENGER",
    OTHER = "OTHER",
  }

  export const PhoneNumberMessengerLabels = {
    [PhoneNumberMessenger.WHATSAPP]: "Whatsapp",
    [PhoneNumberMessenger.TELEGRAM]: "Telegram",
    [PhoneNumberMessenger.MESSENGER]: "Messenger",
    [PhoneNumberMessenger.OTHER]: "Other",
  };

  export const categories = [
    { code: "APPAREL_STORE", name: "Apparel Store" },
    { code: "ART_GALLERY", name: "Art Gallery" },
    { code: "AUTOMOTIVE_STORE", name: "Automotive Store" },
    { code: "BAKERY", name: "Bakery" },
    { code: "BEAUTY_SUPPLY_STORE", name: "Beauty Supply Store" },
    { code: "BOOKSTORE", name: "Bookstore" },
    { code: "CANDY_STORE", name: "Candy Store" },
    { code: "CAR_DEALERSHIP", name: "Car Dealership" },
    { code: "CLOTHING_STORE", name: "Clothing Store" },
    { code: "COMPUTER_STORE", name: "Computer Store" },
    { code: "CONVENIENCE_STORE", name: "Convenience Store" },
    { code: "COSMETICS_STORE", name: "Cosmetics Store" },
    { code: "DEPARTMENT_STORE", name: "Department Store" },
    { code: "ELECTRONICS_STORE", name: "Electronics Store" },
    { code: "FLORIST", name: "Florist" },
    { code: "FURNITURE_STORE", name: "Furniture Store" },
    { code: "GIFT_SHOP", name: "Gift Shop" },
    { code: "GROCERY_STORE", name: "Grocery Store" },
    { code: "HARDWARE_STORE", name: "Hardware Store" },
    { code: "HOME_GOODS_STORE", name: "Home Goods Store" },
    { code: "JEWELRY_STORE", name: "Jewelry Store" },
    { code: "LIQUOR_STORE", name: "Liquor Store" },
    { code: "MALL", name: "Mall" },
    { code: "MATTRESS_STORE", name: "Mattress Store" },
    { code: "MUSIC_STORE", name: "Music Store" },
    { code: "OFFICE_SUPPLIES_STORE", name: "Office Supplies Store" },
    { code: "OPTICAL_STORE", name: "Optical Store" },
    { code: "OUTDOOR_STORE", name: "Outdoor Store" },
    { code: "PET_STORE", name: "Pet Store" },
    { code: "PHARMACY", name: "Pharmacy" },
    { code: "SHOE_STORE", name: "Shoe Store" },
    { code: "SPORTING_GOODS_STORE", name: "Sporting Goods Store" },
    { code: "SUPERMARKET", name: "Supermarket" },
    { code: "TOY_STORE", name: "Toy Store" },
    { code: "VIDEO_GAME_STORE", name: "Video Game Store" },
    { code: "WINE_STORE", name: "Wine Store" },
    { code: "ARTS_AND_CRAFTS_STORE", name: "Arts and Crafts Store" },
    { code: "BEAUTY_SALON", name: "Beauty Salon" },
    { code: "BIKE_SHOP", name: "Bike Shop" },
    { code: "BRIDAL_SHOP", name: "Bridal Shop" },
    { code: "CAR_REPAIR_SHOP", name: "Car Repair Shop" },
    { code: "CELL_PHONE_STORE", name: "Cell Phone Store" },
    { code: "CHOCOLATE_SHOP", name: "Chocolate Shop" },
    { code: "COFFEE_SHOP", name: "Coffee Shop" },
    { code: "COMIC_BOOK_STORE", name: "Comic Book Store" },
    { code: "CUSTOM_TAILOR", name: "Custom Tailor" },
    { code: "DRUGSTORE", name: "Drugstore" },
    { code: "EYEWEAR_STORE", name: "Eyewear Store" },
    { code: "FABRIC_STORE", name: "Fabric Store" },
    { code: "GAMING_CAFE", name: "Gaming Cafe" },
    { code: "HEALTH_FOOD_STORE", name: "Health Food Store" },
    { code: "HOBBY_SHOP", name: "Hobby Shop" },
    { code: "ICE_CREAM_SHOP", name: "Ice Cream Shop" },
    { code: "LINGERIE_STORE", name: "Lingerie Store" },
    { code: "LUGGAGE_STORE", name: "Luggage Store" },
    { code: "MEDICAL_SUPPLY_STORE", name: "Medical Supply Store" },
    { code: "NAIL_SALON", name: "Nail Salon" },
    { code: "PAWN_SHOP", name: "Pawn Shop" },
    { code: "PERFUME_STORE", name: "Perfume Store" },
    { code: "PIZZA_DELIVERY", name: "Pizza Delivery" },
    { code: "PRINT_SHOP", name: "Print Shop" },
    { code: "RECORD_STORE", name: "Record Store" },
    { code: "SHOE_REPAIR_SHOP", name: "Shoe Repair Shop" },
    { code: "SPA", name: "Spa" },
    { code: "SPORTS_BAR", name: "Sports Bar" },
    { code: "SURF_SHOP", name: "Surf Shop" },
    { code: "TATTOO_PARLOR", name: "Tattoo Parlor" },
    { code: "THRIFT_STORE", name: "Thrift Store" },
    { code: "TIRE_SHOP", name: "Tire Shop" },
    { code: "TOBACCONIST", name: "Tobacconist" },
    { code: "TUXEDO_SHOP", name: "Tuxedo Shop" },
    { code: "USED_BOOKSTORE", name: "Used Bookstore" },
    { code: "VAPOR_STORE", name: "Vapor Store" },
    { code: "WIG_STORE", name: "Wig Store" },
    { code: "WINDOW_TREATMENT_STORE", name: "Window Treatment Store" },
    { code: "YOGA_STUDIO", name: "Yoga Studio" },
    { code: "ADULT_STORE", name: "Adult Store" },
    { code: "ANTIQUE_STORE", name: "Antique Store" },
    { code: "AQUARIUM_STORE", name: "Aquarium Store" },
    { code: "ARCADE", name: "Arcade" },
    { code: "ARCHERY_STORE", name: "Archery Store" },
    { code: "ART_SUPPLIES_STORE", name: "Art Supplies Store" },
    {
      code: "AUDIOVISUAL_EQUIPMENT_STORE",
      name: "Audiovisual Equipment Store",
    },
    { code: "AUTO_GLASS_SHOP", name: "Auto Glass Shop" },
    { code: "BAGS_AND_LUGGAGE_STORE", name: "Bags and Luggage Store" },
    {
      code: "BATH_AND_BODY_PRODUCTS_STORE",
      name: "Bath and Body Products Store",
    },
    { code: "BEAUTY_SCHOOL", name: "Beauty School" },
    { code: "BED_AND_BREAKFAST", name: "Bed and Breakfast" },
    { code: "BEER_STORE", name: "Beer Store" },
    { code: "BIKE_RENTAL", name: "Bike Rental" },
    { code: "BOAT_RENTAL_SERVICE", name: "Boat Rental Service" },
    { code: "BOTTLE_SHOP", name: "Bottle Shop" },
    { code: "BREWERY", name: "Brewery" },
    { code: "BRIDAL_SALON", name: "Bridal Salon" },
    { code: "BUILDING_MATERIALS_STORE", name: "Building Materials Store" },
    { code: "CAMERA_STORE", name: "Camera Store" },
    { code: "CAR_WASH", name: "Car Wash" },
    { code: "CATERING_COMPANY", name: "Catering Company" },
    { code: "CHEESE_SHOP", name: "Cheese Shop" },
    { code: "CHILDREN_S_CLOTHING_STORE", name: "Children's Clothing Store" },
    { code: "CIGAR_SHOP", name: "Cigar Shop" },
    { code: "COLLECTIBLES_STORE", name: "Collectibles Store" },
    { code: "CRAFT_BEER_STORE", name: "Craft Beer Store" },
    { code: "CRAFT_STORE", name: "Craft Store" },
    { code: "DAY_CARE_CENTER", name: "Day Care Center" },
    { code: "DESSERT_SHOP", name: "Dessert Shop" },
    { code: "DISCOUNT_STORE", name: "Discount Store" },
    { code: "DIVE_SHOP", name: "Dive Shop" },
    { code: "DOUGHNUT_SHOP", name: "Doughnut Shop" },
    { code: "DRIVING_SCHOOL", name: "Driving School" },
    { code: "DUTY_FREE_SHOP", name: "Duty-Free Shop" },
    { code: "ETHNIC_GROCERY_STORE", name: "Ethnic Grocery Store" },
    { code: "FARMERS_MARKET", name: "Farmers Market" },
    { code: "FIREWORKS_STORE", name: "Fireworks Store" },
    { code: "FISH_MARKET", name: "Fish Market" },
    { code: "FLY_FISHING_STORE", name: "Fly Fishing Store" },
    { code: "GAMBLING_SUPPLY_STORE", name: "Gambling Supply Store" },
    { code: "GLASS_REPAIR_SERVICE", name: "Glass Repair Service" },
    { code: "GO_KART_TRACK", name: "Go-Kart Track" },
    { code: "GUITAR_STORE", name: "Guitar Store" },
    { code: "GUN_STORE", name: "Gun Store" },
    { code: "HEAD_SHOP", name: "Head Shop" },
    { code: "HEATING_EQUIPMENT_SUPPLIER", name: "Heating Equipment Supplier" },
    { code: "HERB_SHOP", name: "Herb Shop" },
    { code: "HOTEL_SUPPLY_STORE", name: "Hotel Supply Store" },
    { code: "HYDROPONICS_STORE", name: "Hydroponics Store" },
    { code: "KAYAKING_CENTER", name: "Kayaking Center" },
    { code: "KIOSK", name: "Kiosk" },
    { code: "KITE_SHOP", name: "Kite Shop" },
    { code: "KITCHEN_SUPPLY_STORE", name: "Kitchen Supply Store" },
    { code: "KITE_BOARDING_SCHOOL", name: "Kite Boarding School" },
    { code: "KNIFE_SHARPENING_SERVICE", name: "Knife Sharpening Service" },
    { code: "LAMP_SHADE_SUPPLIER", name: "Lamp Shade Supplier" },
    { code: "LANDSCAPE_SUPPLY_STORE", name: "Landscape Supply Store" },
    { code: "LAUNDRY_SUPPLY_STORE", name: "Laundry Supply Store" },
    { code: "LEATHER_REPAIR_SERVICE", name: "Leather Repair Service" },
    { code: "LIGHTING_STORE", name: "Lighting Store" },
    { code: "LOCKSMITH", name: "Locksmith" },
    { code: "LUMBER_STORE", name: "Lumber Store" },
    { code: "MAGIC_STORE", name: "Magic Store" },
    { code: "MARINA", name: "Marina" },
    { code: "MATTRESS_MANUFACTURER", name: "Mattress Manufacturer" },
    { code: "MATTRESS_STORE", name: "Mattress Store" },
    { code: "MOTORCYCLE_SHOP", name: "Motorcycle Shop" },
    { code: "MOTOR_HOME_DEALER", name: "Motor Home Dealer" },
    { code: "MOTOR_HOME_RENTAL_AGENCY", name: "Motor Home Rental Agency" },
    { code: "MOTOR_HOME_SERVICE", name: "Motor Home Service" },
    { code: "MOTORCYCLE_DEALER", name: "Motorcycle Dealer" },
    { code: "MOTORCYCLE_REPAIR_SHOP", name: "Motorcycle Repair Shop" },
    { code: "MOTORCYCLE_SHOP", name: "Motorcycle Shop" },
    { code: "MUSIC_LESSON", name: "Music Lesson" },
    { code: "MUSIC_STORE", name: "Music Store" },
    { code: "NEW_CAR_DEALER", name: "New Car Dealer" },
    { code: "NURSERY", name: "Nursery" },
    { code: "OUTDOOR_FURNITURE_STORE", name: "Outdoor Furniture Store" },
    { code: "OUTDOOR_GEAR_STORE", name: "Outdoor Gear Store" },
    { code: "PAINT_STORE", name: "Paint Store" },
    { code: "PAINTBALL_STORE", name: "Paintball Store" },
    { code: "PAPER_DISTRIBUTOR", name: "Paper Distributor" },
    { code: "PIANO_STORE", name: "Piano Store" },
    { code: "PLANT_NURSERY", name: "Plant Nursery" },
    {
      code: "PLASTIC_FABRICATION_COMPANY",
      name: "Plastic Fabrication Company",
    },
    { code: "POOL_CLEANING_SERVICE", name: "Pool Cleaning Service" },
    { code: "POOL_STORE", name: "Pool Store" },
    { code: "POOL_SUPPLY_STORE", name: "Pool Supply Store" },
    { code: "POST_OFFICE", name: "Post Office" },
    { code: "PUBLIC_MARKET", name: "Public Market" },
    { code: "PUBLIC_SWIMMING_POOL", name: "Public Swimming Pool" },
    { code: "RAFT_TRIP_OUTFITTER", name: "Raft Trip Outfitter" },
    { code: "RV_RENTAL_AGENCY", name: "RV Rental Agency" },
    { code: "RV_REPAIR_SHOP", name: "RV Repair Shop" },
    { code: "RV_STORAGE_FACILITY", name: "RV Storage Facility" },
    { code: "RV_SUPPLIER", name: "RV Supplier" },
    { code: "RV_TRAILER_DEALER", name: "RV Trailer Dealer" },
    { code: "RV_TRAINING_SCHOOL", name: "RV Training School" },
    { code: "SCUBA_DIVING_CENTER", name: "Scuba Diving Center" },
    { code: "SECOND_HAND_SHOP", name: "Second-Hand Shop" },
    { code: "SEWING_SHOP", name: "Sewing Shop" },
    { code: "SHOOTING_RANGE", name: "Shooting Range" },
    { code: "SKATE_SHOP", name: "Skate Shop" },
    { code: "SKI_RENTAL_SERVICE", name: "Ski Rental Service" },
    { code: "SKI_REPAIR_SERVICE", name: "Ski Repair Service" },
    { code: "SKI_RESORT", name: "Ski Resort" },
    { code: "SNOWBOARD_RENTAL_SERVICE", name: "Snowboard Rental Service" },
    { code: "SNOWBOARD_REPAIR_SERVICE", name: "Snowboard Repair Service" },
    { code: "SNOWMOBILE_DEALER", name: "Snowmobile Dealer" },
    { code: "SNOWMOBILE_RENTAL_SERVICE", name: "Snowmobile Rental Service" },
    { code: "SNOWMOBILE_REPAIR_SHOP", name: "Snowmobile Repair Shop" },
    { code: "SPA_RESORT", name: "Spa Resort" },
    { code: "SURF_SCHOOL", name: "Surf School" },
    { code: "SWIMMING_POOL_SUPPLY_STORE", name: "Swimming Pool Supply Store" },
    { code: "SYNAGOGUE", name: "Synagogue" },
    { code: "TAILOR_SHOP", name: "Tailor Shop" },
    { code: "TANNING_SALON", name: "Tanning Salon" },
    { code: "TATTOO_SHOP", name: "Tattoo Shop" },
    { code: "TEA_STORE", name: "Tea Store" },
    { code: "THRIFT_STORE", name: "Thrift Store" },
    { code: "TOOL_RENTAL_SERVICE", name: "Tool Rental Service" },
    { code: "TOY_STORE", name: "Toy Store" },
    { code: "TRAILER_RENTAL_SERVICE", name: "Trailer Rental Service" },
    { code: "TRAVEL_AGENCY", name: "Travel Agency" },
    { code: "TREE_FARM", name: "Tree Farm" },
    { code: "USED_APPLIANCE_STORE", name: "Used Appliance Store" },
    { code: "USED_CD_STORE", name: "Used CD Store" },
    { code: "USED_COMPUTER_STORE", name: "Used Computer Store" },
    { code: "USED_FURNITURE_STORE", name: "Used Furniture Store" },
    { code: "USED_GAME_STORE", name: "Used Game Store" },
    { code: "USED_RECORD_STORE", name: "Used Record Store" },
    { code: "USED_BOOKSTORE", name: "Used Bookstore" },
    { code: "USED_VIDEO_GAME_STORE", name: "Used Video Game Store" },
    { code: "VACUUM_CLEANER_STORE", name: "Vacuum Cleaner Store" },
    { code: "VETERINARY_PHARMACY", name: "Veterinary Pharmacy" },
    { code: "VINTAGE_CLOTHING_STORE", name: "Vintage Clothing Store" },
    {
      code: "VITAMIN_AND_SUPPLEMENT_STORE",
      name: "Vitamin and Supplement Store",
    },
    { code: "WATCH_STORE", name: "Watch Store" },
    {
      code: "WATER_SOFTENING_EQUIPMENT_SUPPLIER",
      name: "Water Softening Equipment Supplier",
    },
    { code: "WIG_STORE", name: "Wig Store" },
    { code: "WINDOW_TREATMENT_STORE", name: "Window Treatment Store" },
    { code: "WINE_BAR", name: "Wine Bar" },
    { code: "WINE_STORE", name: "Wine Store" },
    { code: "WOMEN_S_CLOTHING_STORE", name: "Women's Clothing Store" },
    { code: "YARN_STORE", name: "Yarn Store" },
  ];
}

export default StoresEnum;
