namespace ProductsEnum {
  export const categories = [
    { code: "ACCESSORIES", name: "Accessories" },
    { code: "AGRICULTURE_AND_LIVESTOCK", name: "Agriculture and Livestock" },
    { code: "ANIMAL_PRODUCTS", name: "Animal Products" },
    { code: "APPLIANCES", name: "Appliances" },
    { code: "AUDIO_PRODUCTS", name: "Audio Products" },
    { code: "AUTOMOTIVE", name: "Automotive" },
    { code: "AUTOMOTIVE_PARTS", name: "Automotive Parts" },
    { code: "BABY_PRODUCTS", name: "Baby Products" },
    { code: "BEVERAGES", name: "Beverages" },
    { code: "BOARD_GAMES", name: "Board Games" },
    { code: "BOOKS", name: "Books" },
    { code: "BUSINESS_PRODUCTS", name: "Business Products" },
    { code: "CAMPING_PRODUCTS", name: "Camping Products" },
    { code: "CDs_AND_DVDs", name: "CDs and DVDs" },
    { code: "CLEANING_PRODUCTS", name: "Cleaning Products" },
    { code: "CLEANING_SUPPLIES", name: "Cleaning Supplies" },
    { code: "CLOTHING", name: "Clothing" },
    { code: "COMPUTERS", name: "Computers" },
    {
      code: "CONSTRUCTION_AND_REMODELING",
      name: "Construction and Remodeling",
    },
    { code: "CONSTRUCTION_MATERIALS", name: "Construction Materials" },
    { code: "COSMETICS", name: "Cosmetics" },
    { code: "CRAFTS", name: "Crafts" },
    { code: "DECOR", name: "Decor" },
    { code: "DIETARY_SUPPLEMENTS", name: "Dietary Supplements" },
    { code: "ELECTRONICS", name: "Electronics" },
    { code: "FABRICS_AND_TRIMS", name: "Fabrics and Trims" },
    { code: "FASHION_ACCESSORIES", name: "Fashion Accessories" },
    { code: "FERRAGENS", name: "Hardware" },
    { code: "FLOWERS_AND_GIFTS", name: "Flowers and Gifts" },
    { code: "FOOD", name: "Food" },
    { code: "FOTOGRAFIA", name: "Photography" },
    { code: "FURNITURE", name: "Furniture" },
    { code: "GARDEN_PRODUCTS", name: "Garden Products" },
    { code: "HAIR_PRODUCTS", name: "Hair Products" },
    { code: "HARDWARE", name: "Hardware" },
    { code: "HEALTH_AND_WELLNESS", name: "Health and Wellness" },
    { code: "HOME_PRODUCTS", name: "Home Products" },
    { code: "HOUSEHOLD_ITEMS", name: "Household Items" },
    { code: "HOUSEWARES", name: "Housewares" },
    { code: "HYGIENE_PRODUCTS", name: "Hygiene Products" },
    { code: "INSTRUMENTS", name: "Musical Instruments" },
    { code: "IT_EQUIPMENT", name: "IT Equipment" },
    { code: "JEWELRY", name: "Jewelry" },
    { code: "LAB_EQUIPMENT", name: "Lab Equipment" },
    { code: "MAKEUP", name: "Makeup" },
    { code: "MATERIALS", name: "Materials" },
    { code: "MUSICAL_INSTRUMENTS", name: "Musical Instruments" },
    { code: "OFFICE_EQUIPMENT", name: "Office Equipment" },
    { code: "OUTDOOR_ACTIVITIES", name: "Outdoor Activities" },
    { code: "PACKAGING", name: "Packaging" },
    { code: "PAINTING_SUPPLIES", name: "Painting Supplies" },
    { code: "PARTY_SUPPLIES", name: "Party Supplies" },
    { code: "PERSONAL_CARE", name: "Personal Care" },
    { code: "PET_SUPPLIES", name: "Pet Supplies" },
    { code: "PHOTOGRAPHY_PRODUCTS", name: "Photography Products" },
    { code: "POOL_PRODUCTS", name: "Pool Products" },
    { code: "PROMOTIONAL_PRODUCTS", name: "Promotional Products" },
    { code: "RENOVATION_PRODUCTS", name: "Renovation Products" },
    { code: "RESTAURANT_SUPPLIES", name: "Restaurant Supplies" },
    { code: "SAFETY_PRODUCTS", name: "Safety Products" },
    { code: "SCHOOL_SUPPLIES", name: "School Supplies" },
    { code: "SCULPTURE_PRODUCTS", name: "Sculpture Products" },
    { code: "SHOES", name: "Shoes" },
    { code: "SOUND_EQUIPMENT", name: "Sound Equipment" },
    { code: "SPORTING_GOODS", name: "Sporting Goods" },
    { code: "SPORTS_EQUIPMENT", name: "Sports Equipment" },
    { code: "STATIONERY", name: "Stationery" },
    { code: "TOOLS", name: "Tools" },
    { code: "TOYS", name: "Toys" },
    { code: "TRAVEL_AND_TOURISM", name: "Travel and Tourism" },
    { code: "VEHICLE_PARTS", name: "Vehicle Parts" },
    { code: "VIDEO_GAMES", name: "Video Games" },
    { code: "WATCHES", name: "Watches" },
  ];
}

export default ProductsEnum;
